version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: certificate_ledger_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: certificate_ledger
      # MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
